apiVersion: apps/v1
kind: Deployment
metadata:
  name: ampa-2.3
  namespace: kube-system
  labels:
    app: ampa-2.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ampa-2.3
  template:
    metadata:
      labels:
        app: ampa-2.3
    spec:
      volumes:
        - name: xls-data-ampa
          persistentVolumeClaim:
            claimName: nfs-ampa-pvc
        - name: static-ampa
          persistentVolumeClaim:
            claimName: nfs-static-pvc
      containers:
      - name: ampa
        image: 172.18.1.46:5000/ampa:2.3
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
          - mountPath: /code/xls
            name: xls-data-ampa
          - mountPath: /usr/share/nginx/html
            name: static-ampa