apiVersion: apps/v1
kind: Deployment
metadata:
  name: ampa-3.1
  namespace: kube-system
  labels:
    app: ampa-3.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ampa-3.1
  template:
    metadata:
      labels:
        app: ampa-3.1
    spec:
      volumes:
        - name: xls-data-ampa
          persistentVolumeClaim:
            claimName: nfs-ampa-pvc
        - name: static-ampa
          persistentVolumeClaim:
            claimName: nfs-static-pvc
      containers:
      - name: ampa
        image: 172.18.1.46:5000/ampa:3.1
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
          - mountPath: /code/xls
            name: xls-data-ampa
          - mountPath: /code/static
            name: static-ampa
