apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-static-pv
  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /var/nfsserver/k8sdata/static
    server: 172.18.1.223