apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: jprats@systemadmin.es
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: k3s-systemadmin
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: k3s-systemadmin
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  #commonName: ampa.systemadmin.es
  dnsNames:
    - ampa.systemadmin.es
    - static.ampa.systemadmin.es
