# Generated by Django 3.1.5 on 2021-01-30 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('html_message', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='category',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['ordre'], name='peticions_c_ordre_e00693_idx'),
        ),
        migrations.AddField(
            model_name='junta',
            name='issues',
            field=models.ManyToManyField(related_name='juntes', to='peticions.Issue'),
        ),
        migrations.AddIndex(
            model_name='junta',
            index=models.Index(fields=['-updated_at'], name='peticions_j_updated_7c2009_idx'),
        ),
    ]
