# Generated by Django 3.1.5 on 2021-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0002_auto_20210130_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
