# Generated by Django 3.1.5 on 2021-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20201128_1119'),
        ('peticions', '0003_junta_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='votacions',
            field=models.ManyToManyField(related_name='juntes', to='voting.Election'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='html_message',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='html_message',
            field=models.TextField(blank=True, default=None, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='junta',
            name='html_message',
            field=models.TextField(blank=True, default='', max_length=50000, null=True),
        ),
    ]
