# Generated by Django 3.1.5 on 2021-02-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0005_auto_20210206_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ampa',
            field=models.BooleanField(default=False),
        ),
    ]
