# Generated by Django 3.1.5 on 2021-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0006_comment_ampa'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='celebracio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
