# Generated by Django 3.1.5 on 2021-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0007_junta_celebracio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junta',
            options={'ordering': ['-celebracio']},
        ),
        migrations.RemoveIndex(
            model_name='junta',
            name='peticions_j_updated_7c2009_idx',
        ),
        migrations.AddIndex(
            model_name='junta',
            index=models.Index(fields=['-celebracio'], name='peticions_j_celebra_81f882_idx'),
        ),
    ]
