# Generated by Django 3.1.5 on 2021-02-21 15:45

from django.db import migrations, models
import django.db.models.deletion

def forward(apps, schema_editor):
    try:
        Comment = apps.get_model("peticions", "Comment")
        Representant = apps.get_model("peticions", "Representant")

        try:
            representant_ampa = Representant.objects.filter(name="AMPA")[0]
        except:
            representant_ampa = None

        if not representant_ampa:
            representant_ampa = Representant(name="AMPA")
            representant_ampa.save()

        for comment in Comment.objects.all():
            if comment.ampa:
                comment.representant = representant_ampa
                comment.save()
    except:
        pass
            

class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0009_auto_20210221_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='representant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='peticions.representant'),
        ),
        migrations.RunPython(forward),
        migrations.RemoveField(
            model_name='comment',
            name='ampa',
        ),
    ]
