# Generated by Django 3.1.5 on 2021-03-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0010_auto_20210221_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='representant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='peticions.representant'),
        ),
    ]
