# Generated by Django 3.1.5 on 2021-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0011_issue_representant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('a', 'esborrany'), ('g', 'proposada a junta'), ('p', 'a espera de resposta'), ('z', 'tancada')], default='a', max_length=1),
        ),
    ]
