# Generated by Django 3.1.5 on 2021-03-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0012_auto_20210307_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('a', 'esborrany'), ('g', 'proposada a junta'), ('p', 'esperant resposta'), ('z', 'tancada')], default='a', max_length=1),
        ),
    ]
