# Generated by Django 3.1.5 on 2021-03-13 15:16

from django.db import migrations, models
from django.utils.text import slugify

def forward(apps, schema_editor):
    Junta = apps.get_model("peticions", "Junta")

    for junta in Junta.objects.all():
        if not junta.slug:
            junta.slug = slugify(junta.name, allow_unicode=False)
        junta.save()

    Issue = apps.get_model("peticions", "Issue")

    for issue in Issue.objects.all():
        if not issue.slug:
            issue.slug = slugify(issue.titol, allow_unicode=False)
        issue.save()

class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0014_auto_20210307_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default=None, blank=True, null=True, max_length=256),
        ),
        migrations.AddField(
            model_name='junta',
            name='slug',
            field=models.SlugField(default=None, blank=True, null=True, max_length=256),
        ),
        migrations.RunPython(forward),
    ]
