# Generated by Django 3.1.5 on 2021-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0018_junta_peu_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('a', 'esborrany'), ('g', 'proposada a junta'), ('p', 'esperant resposta'), ('y', 'rebutjada'), ('z', 'tancada')], default='a', max_length=1),
        ),
    ]
