# Generated by Django 3.1.5 on 2021-05-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0029_wordtemplate'),
        ('peticions', '0019_auto_20210509_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='wordtemplate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juntes', to='cole.wordtemplate'),
        ),
    ]
