# Generated by Django 3.1.5 on 2021-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0044_auto_20211117_1859'),
        ('peticions', '0020_junta_wordtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='classes',
            field=models.ManyToManyField(related_name='issues', to='cole.Classe'),
        ),
    ]
