apiVersion: apps/v1
kind: Deployment
metadata:
  name: ampa-1.1
  namespace: kube-system
  labels:
    app: ampa-1.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ampa-1.1
  template:
    metadata:
      labels:
        app: ampa-1.1
    spec:
      containers:
      - name: ampa
        image: 172.18.1.46:5000/ampa:1.1
        ports:
        - name: http
          containerPort: 8000
