apiVersion: apps/v1
kind: Deployment
metadata:
  name: ampa-1.1
  namespace: ampa
  labels:
    app: ampa-1.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ampa-1.1
  template:
    metadata:
      labels:
        app: ampa-1.1
    spec:
      containers:
      - name: ampa
        image: django/ampa:1.1
        ports:
        - containerPort: 8000