apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: ampa.systemadmin.es
    http:
      paths:
      - backend:
          serviceName: ampa-11-svc
          servicePort: 80
