# Generated by Django 3.0.5 on 2020-10-14 19:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('invite', models.CharField(max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='?', max_length=256)),
                ('curs', models.CharField(default='?', max_length=256)),
                ('ultim_email', models.DateTimeField(blank=True, default=None, null=True)),
                ('ready_to_send', models.BooleanField(default=False)),
                ('delegat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegatsclasses', to=settings.AUTH_USER_MODEL)),
                ('subdelegat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdelegatsclasses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=256)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='cole.Classe')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_llista', models.IntegerField()),
                ('nom', models.CharField(max_length=256)),
                ('cognom1', models.CharField(max_length=256)),
                ('cognom2', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('naixement', models.DateTimeField(blank=True, null=True)),
                ('tutor1', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('telf_tutor1', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('tutor1_cessio', models.BooleanField(default=False, help_text='Accepto que les meves dades es facilitin al delegat i al grup classe per finalitats de comunicacions: enviament de mails, creació grup whatsapp, etc. acceptant fer un ús responsable i no facilitar a tercers les dades del grup classe que proporcionarà el delegat')),
                ('tutor2', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('telf_tutor2', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('tutor2_cessio', models.BooleanField(default=False, help_text='Accepto que les meves dades es facilitin al delegat i al grup classe per finalitats de comunicacions: enviament de mails, creació grup whatsapp, etc. acceptant fer un ús responsable i no facilitar a tercers les dades del grup classe que proporcionarà el delegat')),
                ('emails', models.TextField(blank=True, default=None, max_length=256, null=True)),
                ('validat', models.BooleanField(default=False, help_text='He comprovat totes les dades i són correctes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnes', to='cole.Classe')),
            ],
            options={
                'ordering': ['num_llista', 'classe'],
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['updated_at'], name='cole_fileup_updated_c675a2_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['-updated_at'], name='cole_fileup_updated_1f93f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'curs', 'delegat')},
        ),
        migrations.AddIndex(
            model_name='alumne',
            index=models.Index(fields=['num_llista', 'classe'], name='cole_alumne_num_lli_ce2b14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alumne',
            unique_together={('num_llista', 'nom', 'cognom1', 'classe')},
        ),
    ]
