# Generated by Django 3.0.5 on 2020-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='email_delegat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='email_subdelegat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='latest_export',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='nom_delegat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='nom_subdelegat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='telefon_delegat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='telefon_subdelegat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='tutor',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='waiting_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classe',
            name='curs',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(default='', max_length=256),
        ),
    ]
