# Generated by Django 3.0.5 on 2020-10-29 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0002_versio_1_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('upload_path', models.CharField(max_length=256)),
                ('filepath', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=256)),
                ('html_message', models.TextField(blank=True, default=None, max_length=10000, null=True)),
                ('email_from', models.CharField(default='', max_length=256)),
                ('email_reply_to', models.CharField(default=None, max_length=256)),
                ('nomes_delegats', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('0', 'borrador'), ('1', 'enviament programat'), ('2', 'enviant...'), ('3', 'enviament completat')], default='0', max_length=1)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(related_name='mailings', to='cole.FileAttachment')),
                ('classes', models.ManyToManyField(related_name='mailings', to='cole.Classe')),
            ],
            options={
                'ordering': ['-updated_at', 'status'],
            },
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['-created_at'], name='cole_fileat_created_c75870_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['-updated_at', 'status'], name='cole_mailin_updated_e1d8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='mailing',
            index=models.Index(fields=['status'], name='cole_mailin_status_c43ac0_idx'),
        ),
    ]
