# Generated by Django 3.0.5 on 2020-10-27 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0002_versio_1_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=256)),
                ('html_message', models.TextField(blank=True, default=None, max_length=10000, null=True)),
                ('email_from', models.CharField(default='', max_length=256)),
                ('email_reply_to', models.CharField(default=None, max_length=256)),
                ('nomes_delegats', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('D', 'borrador'), ('P', 'enviament programat'), ('S', 'enviant...'), ('C', 'enviament completat')], default='D', max_length=1)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(related_name='mailings', to='cole.Classe')),
            ],
        ),
    ]
