# Generated by Django 3.0.5 on 2020-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0003_auto_20201029_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email_from',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='email_reply_to',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('0', 'borrador'), ('1', 'enviament programat'), ('2', 'enviant...'), ('3', 'enviament completat'), ('E', "error general d'enviament")], default='0', max_length=1),
        ),
    ]
