# Generated by Django 3.0.5 on 2020-11-28 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0005_curs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumne',
            old_name='emails',
            new_name='email_tutor1',
        ),
        migrations.AddField(
            model_name='alumne',
            name='email_tutor2',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]

