# Generated by Django 3.0.5 on 2020-11-28 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0006_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curs', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['curs'],
            },
        ),
        migrations.AlterField(
            model_name='alumne',
            name='email_tutor1',
            field=models.TextField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='email_tutor2',
            field=models.TextField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AddIndex(
            model_name='curs',
            index=models.Index(fields=['curs'], name='cole_curs_curs_1f7a08_idx'),
        ),
        migrations.AddField(
            model_name='classe',
            name='curs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cole.Curs'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'curs', 'delegat')},
        ),
    ]
