# Generated by Django 3.0.5 on 2020-11-28 14:53

from django.db import migrations, models
import django.db.models.deletion

def forward(apps, schema_editor):
    Alumne = apps.get_model("cole", "Alumne")
    for alumne in Alumne.objects.all():
        alumne.classes.add(alumne.classe)

class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0007_auto_20201128_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='classes',
            field=models.ManyToManyField(related_name='alumnes', to='cole.Classe'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_alumnes', to='cole.Classe'),
        ),
        migrations.RunPython(forward)
    ]
