# Generated by Django 3.0.5 on 2020-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0008_alumne_to_many'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumne',
            options={'ordering': ['num_llista', 'cognom1', 'cognom2']},
        ),
        migrations.RemoveIndex(
            model_name='alumne',
            name='cole_alumne_num_lli_ce2b14_idx',
        ),
        migrations.AlterUniqueTogether(
            name='alumne',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alumne',
            name='classe',
        ),
    ]
