# Generated by Django 3.0.5 on 2020-11-29 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0009_auto_20201128_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='baixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExtraInfoAlumne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcio', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('dades', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrainfo', to='cole.Alumne')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cole.FileAttachment')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='extrainfoalumne',
            index=models.Index(fields=['updated_at'], name='cole_extrai_updated_06e41a_idx'),
        ),
        migrations.AddIndex(
            model_name='extrainfoalumne',
            index=models.Index(fields=['-updated_at'], name='cole_extrai_updated_b61a1c_idx'),
        ),
    ]
