# Generated by Django 3.0.5 on 2020-11-29 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0009_auto_20201128_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='baixa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExtraInfoAlumne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcio', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('dades', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extainfo', to='cole.Alumne')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cole.FileAttachment')),
            ],
        ),
    ]
