# Generated by Django 3.1.5 on 2021-02-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0013_auto_20210203_1901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curs',
            unique_together={('curs', 'modalitat')},
        ),
    ]
