# Generated by Django 3.1.5 on 2021-02-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0014_auto_20210203_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nom']},
        ),
    ]
