# Generated by Django 3.1.5 on 2021-02-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0016_auto_20210206_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['curs', 'etapa', 'nom']},
        ),
    ]
