# Generated by Django 3.1.5 on 2021-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0017_auto_20210206_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.AddField(
            model_name='etapa',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
    ]
