# Generated by Django 3.1.5 on 2021-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0018_auto_20210214_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='naixement',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
