# Generated by Django 3.1.5 on 2021-03-06 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0019_auto_20210220_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('likable_issues', models.BooleanField(default=False)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitats', to='cole.fileattachment')),
            ],
        ),
    ]
