# Generated by Django 3.1.5 on 2021-03-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0011_issue_representant'),
        ('cole', '0020_entitat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='representant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='peticions.representant'),
        ),
    ]
