# Generated by Django 3.1.5 on 2021-03-06 15:28

from django.db import migrations, models

def forward(apps, schema_editor):
    User = apps.get_model("cole", "User")
    for user in User.objects.all():
        user.email=user.email.lower()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0021_user_representant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='cole_user_email_c6e51b_idx'),
        ),
        migrations.RunPython(forward)
    ]
