# Generated by Django 3.1.5 on 2021-03-06 17:29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0022_auto_20210306_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitat',
            name='codi_registre',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
