# Generated by Django 3.1.5 on 2021-03-06 17:29

from django.db import migrations, models

def forward(apps, schema_editor):
    Entitat = apps.get_model("cole", "Entitat")
    try:
        entitat_instance = Entitat.objects.all()[0]
        if entitat_instance:
            return
    except:
        pass
    entitat_instance = Entitat()
    entitat_instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0023_entitat_codi_registre'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
