# Generated by Django 3.1.5 on 2021-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0024_entitat_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitat',
            name='codi_registre',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='entitat',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
