# Generated by Django 3.1.5 on 2021-03-07 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0026_auto_20210307_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='cole.classe'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
