# Generated by Django 3.1.5 on 2021-03-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0027_auto_20210307_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitat',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitats', to='cole.fileattachment'),
        ),
    ]
