# Generated by Django 3.1.5 on 2021-09-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0029_wordtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['-curs', 'etapa', 'nom']},
        ),
    ]
