# Generated by Django 3.1.5 on 2021-10-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0034_auto_20211023_1430'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'curs', 'etapa', 'delegat')},
        ),
    ]
