# Generated by Django 3.1.5 on 2021-10-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0035_auto_20211023_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitat',
            name='password_default',
            field=models.CharField(blank=True, default='AMPA00', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
    ]
