# Generated by Django 3.1.5 on 2021-10-30 15:19

from django.db import migrations, models

from datetime import datetime

def forward(apps, schema_editor):
    User = apps.get_model("cole", "User")
    for user_instance in User.objects.all():
        user_instance.last_password_change = datetime.now()
        user_instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0037_auto_20211030_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(forward)
    ]
