# Generated by Django 3.1.5 on 2021-10-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0038_auto_20211030_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
