# Generated by Django 3.1.5 on 2021-11-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0039_user_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='what',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='where',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='email_from',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
