# Generated by Django 3.1.5 on 2021-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0040_auto_20211101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('0', 'borrador'), ('1', 'enviament programat'), ('2', 'enviant...'), ('3', 'completat'), ('E', "error general d'enviament")], default='0', max_length=1),
        ),
    ]
