# Generated by Django 3.1.5 on 2021-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0020_junta_wordtemplate'),
        ('cole', '0041_auto_20211101_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='representants',
            field=models.ManyToManyField(related_name='mailings', to='peticions.Representant'),
        ),
    ]
