# Generated by Django 3.1.5 on 2021-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticions', '0020_junta_wordtemplate'),
        ('cole', '0043_mailing_nomes_representants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='representants',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='mailings', to='peticions.Representant'),
        ),
    ]
