# Generated by Django 3.1.5 on 2021-11-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0044_auto_20211117_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='nomes_plataforma',
            field=models.BooleanField(default=False),
        ),
    ]
