# Generated by Django 3.1.5 on 2021-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole', '0046_auto_20211120_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_colegi',
            field=models.BooleanField(default=False),
        ),
    ]
